name: Build and Push Docker

on:
  workflow_run:
    workflows: []
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/webapp-cicd
          tags:  type=semver,pattern={{version}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: yu-kod/webApp-Manifests
          ref: main
          token: ${{ secrets.PAT }}
          path: webApp-Manifests
      
      - name: Update image tag
        id: update-image-tag
        working-directory: webApp-Manifests
        continue-on-error: true
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ secrets.DOCKER_USERNAME }}/webapp-cicd:${{ steps.meta.outputs.tags }}"' ./main/deployment.yaml
          git diff --name-only --exit-code

      - name: Commit and push
        working-directory: webApp-Manifests
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update image tag to ${{ github.run_number }}"
          git push
        
            
